<a href="https://colab.research.google.com/github/yaswanthdongara/modules/blob/main/DataFrame_7_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("students_marks_25_rows.csv")
print(df)

   Student Name  Mathematics  Science  English  Computer Science  \
0         Aarav           85       78       92                88
1        Aditya           76       84       79                91
2         Arjun           92       89       85                94
3        Bhavya           81       75       88                82
4        Charan           69       72       77                74
5        Deepak           88       91       84                86
6         Divya           95       93       90                96
7       Gautham           73       80       71                78
8        Harsha           84       87       82                85
9        Ishita           91       88       94                90
10      Karthik           77       69       83                76
11        Kavya           89       94       87                91
12        Manoj           68       74       70                79
13      Meghana           93       90       96                89
14       Naveen           80       83       78                85
15       Nikhil           75       77       73                80
16        Pooja           86       89       91                84
17        Rahul           71       68       76                73
18         Riya           90       92       88                95
19        Rohit           82       79       85                81
20       Sanjay           74       81       69                77
21        Sneha           97       95       93                98
22        Varun           79       85       80                83
23        Vijay           87       76       89                88
24         Yash           83       86       81                90

    Social Studies
0               81
1               73
2               90
3               79
4               68
5               89
6               94
7               75
8               80
9               92
10              72
11              88
12              65
13              95
14              81
15              71
16              87
17              70
18              91
19              84
20              76
21              96
22              78
23              85
24              82

In [4]:
#adding a new column by an expression
df["percentage"] = (df["Mathematics"] + df["Science"] + df["English"] + df["Computer Science"] + df["Social Studies"])/5
print(df)

   Student Name  Mathematics  Science  English  Computer Science  \
0         Aarav           85       78       92                88
1        Aditya           76       84       79                91
2         Arjun           92       89       85                94
3        Bhavya           81       75       88                82
4        Charan           69       72       77                74
5        Deepak           88       91       84                86
6         Divya           95       93       90                96
7       Gautham           73       80       71                78
8        Harsha           84       87       82                85
9        Ishita           91       88       94                90
10      Karthik           77       69       83                76
11        Kavya           89       94       87                91
12        Manoj           68       74       70                79
13      Meghana           93       90       96                89
14       Naveen           80       83       78                85
15       Nikhil           75       77       73                80
16        Pooja           86       89       91                84
17        Rahul           71       68       76                73
18         Riya           90       92       88                95
19        Rohit           82       79       85                81
20       Sanjay           74       81       69                77
21        Sneha           97       95       93                98
22        Varun           79       85       80                83
23        Vijay           87       76       89                88
24         Yash           83       86       81                90

    Social Studies  percentage
0               81        84.8
1               73        80.6
2               90        90.0
3               79        81.0
4               68        72.0
5               89        87.6
6               94        93.6
7               75        75.4
8               80        83.6
9               92        91.0
10              72        75.4
11              88        89.8
12              65        71.2
13              95        92.6
14              81        81.4
15              71        75.2
16              87        87.4
17              70        71.6
18              91        91.2
19              84        82.2
20              76        75.4
21              96        95.8
22              78        81.0
23              85        85.0
24              82        84.4

In [6]:
#sort the dataframe data on col name percentage
df.sort_values(["percentage"])

,Student Name,Mathematics,Science,English,Computer Science,Social Studies,percentage
12,Manoj,68,74,70,79,65,71.2
17,Rahul,71,68,76,73,70,71.6
4,Charan,69,72,77,74,68,72.0
15,Nikhil,75,77,73,80,71,75.2
10,Karthik,77,69,83,76,72,75.4
7,Gautham,73,80,71,78,75,75.4
20,Sanjay,74,81,69,77,76,75.4
1,Aditya,76,84,79,91,73,80.6
3,Bhavya,81,75,88,82,79,81.0
22,Varun,79,85,80,83,78,81.0
14,Naveen,80,83,78,85,81,81.4
19,Rohit,82,79,85,81,84,82.2
8,Harsha,84,87,82,85,80,83.6
24,Yash,83,86,81,90,82,84.4
0,Aarav,85,78,92,88,81,84.8
23,Vijay,87,76,89,88,85,85.0
16,Pooja,86,89,91,84,87,87.4
5,Deepak,88,91,84,86,89,87.6
11,Kavya,89,94,87,91,88,89.8
2,Arjun,92,89,85,94,90,90.0
9,Ishita,91,88,94,90,92,91.0
18,Riya,90,92,88,95,91,91.2
13,Meghana,93,90,96,89,95,92.6
6,Divya,95,93,90,96,94,93.6
21,Sneha,97,95,93,98,96,95.8

In [11]:
df[["Student Name","percentage"]].iloc[-1]

Student Name    Yash
percentage      84.4
Name: 24, dtype: object

In [12]:
df.sort_values(["percentage"],ascending=False).head()

,Student Name,Mathematics,Science,English,Computer Science,Social Studies,percentage
21,Sneha,97,95,93,98,96,95.8
6,Divya,95,93,90,96,94,93.6
13,Meghana,93,90,96,89,95,92.6
18,Riya,90,92,88,95,91,91.2
9,Ishita,91,88,94,90,92,91.0

In [14]:
print(df.head())

  Student Name  Mathematics  Science  English  Computer Science  \
0        Aarav           85       78       92                88
1       Aditya           76       84       79                91
2        Arjun           92       89       85                94
3       Bhavya           81       75       88                82
4       Charan           69       72       77                74

   Social Studies  percentage
0              81        84.8
1              73        80.6
2              90        90.0
3              79        81.0
4              68        72.0

after sorting the data, the result is not permanent, to make it permanent we use inplace=True

In [17]:
df.sort_values(["percentage"],ascending=False,inplace=True)

In [18]:
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage
21              96        95.8
6               94        93.6
13              95        92.6
18              91        91.2
9               92        91.0

In [23]:
df["Grade"] = "A+"
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage Grade
21              96        95.8    A+
6               94        93.6    A+
13              95        92.6    A+
18              91        91.2    A+
9               92        91.0    A+

In [24]:
#removing a column
df.drop(columns=["Grade"],inplace=True)
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage
21              96        95.8
6               94        93.6
13              95        92.6
18              91        91.2
9               92        91.0

to make changes permanently use inplace=True

In [25]:
df.drop(columns=["percentage"])
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage
21              96        95.8
6               94        93.6
13              95        92.6
18              91        91.2
9               92        91.0

by default inplace=False

In [27]:
df.drop(columns=["percentage","Mathematics"])
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage
21              96        95.8
6               94        93.6
13              95        92.6
18              91        91.2
9               92        91.0

In [38]:
df.drop(columns=df.columns[2]).head()

,Student Name,Mathematics,English,Computer Science,Social Studies,percentage
21,Sneha,97,93,98,96,95.8
6,Divya,95,90,96,94,93.6
13,Meghana,93,96,89,95,92.6
18,Riya,90,88,95,91,91.2
9,Ishita,91,94,90,92,91.0

In [32]:
#dropping columns by col_number
df.drop(df.columns[2],axis=1).head()

,Student Name,Mathematics,English,Computer Science,Social Studies,percentage
21,Sneha,97,93,98,96,95.8
6,Divya,95,90,96,94,93.6
13,Meghana,93,96,89,95,92.6
18,Riya,90,88,95,91,91.2
9,Ishita,91,94,90,92,91.0

In [40]:
df["cgpa","sgpa"] = None
print(df.head())

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
6         Divya           95       93       90                96
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
9        Ishita           91       88       94                90

    Social Studies  percentage (cgpa, sgpa)
21              96        95.8         None
6               94        93.6         None
13              95        92.6         None
18              91        91.2         None
9               92        91.0         None

In [41]:
df.drop(index=10)

,Student Name,Mathematics,Science,English,Computer Science,Social Studies,percentage,"(cgpa, sgpa)"
21,Sneha,97,95,93,98,96,95.8,None
6,Divya,95,93,90,96,94,93.6,None
13,Meghana,93,90,96,89,95,92.6,None
18,Riya,90,92,88,95,91,91.2,None
9,Ishita,91,88,94,90,92,91.0,None
2,Arjun,92,89,85,94,90,90.0,None
11,Kavya,89,94,87,91,88,89.8,None
5,Deepak,88,91,84,86,89,87.6,None
16,Pooja,86,89,91,84,87,87.4,None
23,Vijay,87,76,89,88,85,85.0,None
0,Aarav,85,78,92,88,81,84.8,None
24,Yash,83,86,81,90,82,84.4,None
8,Harsha,84,87,82,85,80,83.6,None
19,Rohit,82,79,85,81,84,82.2,None
14,Naveen,80,83,78,85,81,81.4,None
22,Varun,79,85,80,83,78,81.0,None
3,Bhavya,81,75,88,82,79,81.0,None
1,Aditya,76,84,79,91,73,80.6,None
7,Gautham,73,80,71,78,75,75.4,None
20,Sanjay,74,81,69,77,76,75.4,None
15,Nikhil,75,77,73,80,71,75.2,None
4,Charan,69,72,77,74,68,72.0,None
17,Rahul,71,68,76,73,70,71.6,None
12,Manoj,68,74,70,79,65,71.2,None

In [46]:
df.drop(index=10,axis=1,inplace=True)
print(df)

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
2         Arjun           92       89       85                94
11        Kavya           89       94       87                91
5        Deepak           88       91       84                86
16        Pooja           86       89       91                84
23        Vijay           87       76       89                88
0         Aarav           85       78       92                88
24         Yash           83       86       81                90
14       Naveen           80       83       78                85
22        Varun           79       85       80                83
3        Bhavya           81       75       88                82
1        Aditya           76       84       79                91
7       Gautham           73       80       71                78
20       Sanjay           74       81       69                77
15       Nikhil           75       77       73                80
4        Charan           69       72       77                74
17        Rahul           71       68       76                73
12        Manoj           68       74       70                79

    Social Studies  percentage (cgpa, sgpa)
21              96        95.8         None
13              95        92.6         None
18              91        91.2         None
2               90        90.0         None
11              88        89.8         None
5               89        87.6         None
16              87        87.4         None
23              85        85.0         None
0               81        84.8         None
24              82        84.4         None
14              81        81.4         None
22              78        81.0         None
3               79        81.0         None
1               73        80.6         None
7               75        75.4         None
20              76        75.4         None
15              71        75.2         None
4               68        72.0         None
17              70        71.6         None
12              65        71.2         None

In [45]:
df.drop(index=[6,19],axis=0,inplace=True)
print(df)

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
13      Meghana           93       90       96                89
18         Riya           90       92       88                95
2         Arjun           92       89       85                94
11        Kavya           89       94       87                91
5        Deepak           88       91       84                86
16        Pooja           86       89       91                84
23        Vijay           87       76       89                88
0         Aarav           85       78       92                88
24         Yash           83       86       81                90
14       Naveen           80       83       78                85
22        Varun           79       85       80                83
3        Bhavya           81       75       88                82
1        Aditya           76       84       79                91
7       Gautham           73       80       71                78
20       Sanjay           74       81       69                77
10      Karthik           77       69       83                76
15       Nikhil           75       77       73                80
4        Charan           69       72       77                74
17        Rahul           71       68       76                73
12        Manoj           68       74       70                79

    Social Studies  percentage (cgpa, sgpa)
21              96        95.8         None
13              95        92.6         None
18              91        91.2         None
2               90        90.0         None
11              88        89.8         None
5               89        87.6         None
16              87        87.4         None
23              85        85.0         None
0               81        84.8         None
24              82        84.4         None
14              81        81.4         None
22              78        81.0         None
3               79        81.0         None
1               73        80.6         None
7               75        75.4         None
20              76        75.4         None
10              72        75.4         None
15              71        75.2         None
4               68        72.0         None
17              70        71.6         None
12              65        71.2         None

In [47]:
df.drop(index=[6,19],axis=0,inplace=True)
print(df)

KeyError: '[6, 19] not found in axis'

In [49]:
df.drop(index=[16,11,13,14,15],axis=0,inplace=True)
print(df)

   Student Name  Mathematics  Science  English  Computer Science  \
21        Sneha           97       95       93                98
18         Riya           90       92       88                95
2         Arjun           92       89       85                94
5        Deepak           88       91       84                86
23        Vijay           87       76       89                88
0         Aarav           85       78       92                88
24         Yash           83       86       81                90
22        Varun           79       85       80                83
3        Bhavya           81       75       88                82
1        Aditya           76       84       79                91
7       Gautham           73       80       71                78
20       Sanjay           74       81       69                77
4        Charan           69       72       77                74
17        Rahul           71       68       76                73
12        Manoj           68       74       70                79

    Social Studies  percentage (cgpa, sgpa)
21              96        95.8         None
18              91        91.2         None
2               90        90.0         None
5               89        87.6         None
23              85        85.0         None
0               81        84.8         None
24              82        84.4         None
22              78        81.0         None
3               79        81.0         None
1               73        80.6         None
7               75        75.4         None
20              76        75.4         None
4               68        72.0         None
17              70        71.6         None
12              65        71.2         None

In [50]:
df.drop(columns=["Social Studies","Science","Computer Science","percentage"],inplace=True)
print(df)

   Student Name  Mathematics  English (cgpa, sgpa)
21        Sneha           97       93         None
18         Riya           90       88         None
2         Arjun           92       85         None
5        Deepak           88       84         None
23        Vijay           87       89         None
0         Aarav           85       92         None
24         Yash           83       81         None
22        Varun           79       80         None
3        Bhavya           81       88         None
1        Aditya           76       79         None
7       Gautham           73       71         None
20       Sanjay           74       69         None
4        Charan           69       77         None
17        Rahul           71       76         None
12        Manoj           68       70         None

In [62]:
df.drop(('cgpa', 'sgpa'), inplace=True, axis=1)
print(df)

   Student Name  Mathematics  English
21        Sneha           97       93
18         Riya           90       88
2         Arjun           92       85
5        Deepak           88       84
23        Vijay           87       89
0         Aarav           85       92
24         Yash           83       81
22        Varun           79       80
3        Bhavya           81       88
1        Aditya           76       79
7       Gautham           73       71
20       Sanjay           74       69
4        Charan           69       77
17        Rahul           71       76
12        Manoj           68       70

In [63]:
print(df.columns.tolist())

['Student Name', 'Mathematics', 'English']

Adding a row to DataFrame

In [64]:
df.loc[len(df)] = ["Gowthami",100,100]
print(df)

   Student Name  Mathematics  English
21        Sneha           97       93
18         Riya           90       88
2         Arjun           92       85
5        Deepak           88       84
23        Vijay           87       89
0         Aarav           85       92
24         Yash           83       81
22        Varun           79       80
3        Bhavya           81       88
1        Aditya           76       79
7       Gautham           73       71
20       Sanjay           74       69
4        Charan           69       77
17        Rahul           71       76
12        Manoj           68       70
15     Gowthami          100      100

In [65]:
df.loc[16]=["Srashta",100]

ValueError: cannot set a row with mismatched columns

In [66]:
df.loc[16]=["Srashta",100,100]

In [67]:
print(df)

   Student Name  Mathematics  English
21        Sneha           97       93
18         Riya           90       88
2         Arjun           92       85
5        Deepak           88       84
23        Vijay           87       89
0         Aarav           85       92
24         Yash           83       81
22        Varun           79       80
3        Bhavya           81       88
1        Aditya           76       79
7       Gautham           73       71
20       Sanjay           74       69
4        Charan           69       77
17        Rahul           71       76
12        Manoj           68       70
15     Gowthami          100      100
16      Srashta          100      100

In [70]:
#editing existing row values
df.loc[20]=["Srashta",100,100]
print(df)

   Student Name  Mathematics  English
21        Sneha           97       93
18         Riya           90       88
2         Arjun           92       85
5        Deepak           88       84
23        Vijay           87       89
0         Aarav           85       92
24         Yash           83       81
22        Varun           79       80
3        Bhavya           81       88
1        Aditya           76       79
7       Gautham           73       71
20      Srashta          100      100
4        Charan           69       77
17        Rahul           71       76
12        Manoj           68       70
15     Gowthami          100      100
16      Srashta          100      100

Knowing about duplicates

In [71]:
df.duplicated()

21    False
18    False
2     False
5     False
23    False
0     False
24    False
22    False
3     False
1     False
7     False
20    False
4     False
17    False
12    False
15    False
16     True
dtype: bool

In [72]:
df[df.duplicated()]

   Student Name  Mathematics  English
16      Srashta          100      100

In [73]:
#dropping duplicate records
df.drop_duplicates(inplace=True)
print(df)

   Student Name  Mathematics  English
21        Sneha           97       93
18         Riya           90       88
2         Arjun           92       85
5        Deepak           88       84
23        Vijay           87       89
0         Aarav           85       92
24         Yash           83       81
22        Varun           79       80
3        Bhavya           81       88
1        Aditya           76       79
7       Gautham           73       71
20      Srashta          100      100
4        Charan           69       77
17        Rahul           71       76
12        Manoj           68       70
15     Gowthami          100      100